import { Product } from './supabase'

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: '1',
    name_ar: 'سيروم فيتامين سي COSRX',
    name_en: 'COSRX Vitamin C Serum',
    price: 12.5,
    category: 'skincare',
    description_ar: 'سيروم فيتامين سي من كوسركس يعمل على توحيد لون البشرة وإضفاء الإشراق والحيوية للبشرة المتعبة',
    description_en: 'COSRX Vitamin C serum brightens and evens skin tone with powerful antioxidants for a radiant complexion',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80'],
    stock: 25,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name_ar: 'كريم الحلزون COSRX 92',
    name_en: 'COSRX Snail 92 All-in-One Cream',
    price: 8.75,
    category: 'skincare',
    description_ar: 'كريم الحلزون المرطب والمغذي للبشرة من كوسركس، مثالي للبشرة الجافة والتالفة',
    description_en: 'COSRX snail mucin cream for deep hydration, repair and soothing of damaged skin',
    images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&q=80'],
    stock: 30,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name_ar: 'واقي الشمس الذهبي Anessa SPF50+',
    name_en: 'Anessa Perfect UV Sunscreen SPF50+',
    price: 15.0,
    category: 'sunscreen',
    description_ar: 'واقي الشمس الذهبي من أنيسا بحماية عالية SPF50+ مقاوم للماء والعرق',
    description_en: 'Anessa perfect UV sunscreen SPF50+ PA++++, water and sweat resistant formula',
    images: ['https://images.unsplash.com/photo-1601049676869-702ea24cfd58?w=600&q=80'],
    stock: 20,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name_ar: 'قناع الطين البركاني إنيسفري',
    name_en: 'Innisfree Super Volcanic Clay Mask',
    price: 6.5,
    category: 'masks',
    description_ar: 'قناع الطين البركاني من إنيسفري ينقي المسام ويزيل الزيوت الزائدة لبشرة نضرة',
    description_en: 'Innisfree volcanic clay mask deeply cleanses pores and controls excess sebum',
    images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&q=80'],
    stock: 40,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name_ar: 'تونر كريمي Laneige',
    name_en: 'Laneige Cream Skin Toner',
    price: 11.0,
    category: 'skincare',
    description_ar: 'تونر كريمي من لانيج يمنح البشرة الترطيب العميق والنعومة الفائقة',
    description_en: 'Laneige cream skin toner for deep moisture and silky smooth skin texture',
    images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80'],
    stock: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name_ar: 'سيروم النياسيناميد Some By Mi',
    name_en: 'Some By Mi Niacinamide 30 Days Serum',
    price: 9.5,
    category: 'skincare',
    description_ar: 'سيروم النياسيناميد من سم باي مي يوحد لون البشرة ويقلل البقع الداكنة في 30 يوم',
    description_en: 'Some By Mi niacinamide serum evens skin tone and fades dark spots in 30 days',
    images: ['https://images.unsplash.com/photo-1570194065650-d99fb4b38176?w=600&q=80'],
    stock: 28,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name_ar: 'احمر شفاه مخملي Romand',
    name_en: 'Romand Zero Velvet Tint',
    price: 5.5,
    category: 'makeup',
    description_ar: 'احمر شفاه مخملي من رومند بألوان عصرية وتثبيت طويل الأمد',
    description_en: 'Romand velvet lip tint with trendy shades and long-lasting matte finish',
    images: ['https://images.unsplash.com/photo-1586495777744-4e6232bf4f3a?w=600&q=80'],
    stock: 50,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name_ar: 'كريم العين Etude House',
    name_en: 'Etude House Moistfull Eye Cream',
    price: 7.5,
    category: 'skincare',
    description_ar: 'كريم العين المرطب من إيتود هاوس يقلل الهالات السوداء ويرطب منطقة العين',
    description_en: 'Etude House moistfull eye cream reduces dark circles and puffiness',
    images: ['https://images.unsplash.com/photo-1617897903246-719242758050?w=600&q=80'],
    stock: 35,
    created_at: new Date().toISOString(),
  },
]
